.TH "Mat< 1, 1, T >" 3 "Fri Mar 11 2022" "Version V2.0" "MatrixVectorHeader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mat< 1, 1, T > \- Base case for recursion\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Matrix\&.hpp>\fP
.PP
Inherits \fBMatBase< 1, 1, T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMat\fP (const \fBMat\fP< 1, 1, T > &m1)"
.br
.ti -1c
.RI "\fBMat\fP (const \fBMatBase\fP< 1, 1, T > &m1)"
.br
.ti -1c
.RI "\fBMat\fP (std::initializer_list< std::initializer_list< T > > v)"
.br
.ti -1c
.RI "template<typename N > \fBMat\fP< 1, 1, T > & \fBoperator*=\fP (const \fBMat\fP< 1, 1, N > &B)"
.br
.ti -1c
.RI "template<typename N > const \fBMat\fP< 1, 1, T > \fBoperator*\fP (const \fBMat\fP< 1, 1, N > &B) const"
.br
.ti -1c
.RI "template<typename N > \fBMat\fP< 1, 1, T > & \fBoperator*=\fP (const N &r)"
.br
.ti -1c
.RI "template<typename N > const \fBMat\fP< 1, 1, T > \fBoperator*\fP (const N &r) const"
.br
.ti -1c
.RI "template<typename N > \fBMat\fP< 1, 1, T > & \fBoperator+=\fP (const \fBMat\fP< 1, 1, N > &B)"
.br
.ti -1c
.RI "template<typename N > const \fBMat\fP< 1, 1, T > \fBoperator+\fP (const \fBMat\fP< 1, 1, N > &B) const"
.br
.ti -1c
.RI "template<typename N > \fBMat\fP< 1, 1, T > & \fBoperator\-=\fP (const \fBMat\fP< 1, 1, N > &B)"
.br
.ti -1c
.RI "template<typename N > const \fBMat\fP< 1, 1, T > \fBoperator\-\fP (const \fBMat\fP< 1, 1, N > &B) const"
.br
.ti -1c
.RI "\fBMat\fP< 1, 1, T > \fBTranspose\fP (void) const"
.br
.ti -1c
.RI "\fBMat\fP< 1, 1, T > \fBSubMatrix\fP (const unsigned int i, const unsigned int j) const"
.br
.RI "base case for submatrix recursion "
.ti -1c
.RI "double \fBDeterminant\fP (void) const"
.br
.RI "Returns the value of [0,0] in the matrix This specialisation is needed for calculating the determinant\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class Mat< 1, 1, T >"Base case for recursion\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP datatype of the matrix 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<typename T > double \fBMat\fP< 1, 1, T >::Determinant (void) const"

.PP
Returns the value of [0,0] in the matrix This specialisation is needed for calculating the determinant\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP the datatype of the matrix 
.RE
.PP
\fBReturns\fP
.RS 4
double the determinant value 
.RE
.PP

.SS "template<typename T > \fBMat\fP< 1, 1, T > \fBMat\fP< 1, 1, T >::SubMatrix (const unsigned int i, const unsigned int j) const"

.PP
base case for submatrix recursion 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP the submatrix 
.RE
.PP
\fBParameters\fP
.RS 4
\fIi\fP the row to skip ( ignored ) 
.br
\fIj\fP the column to skip ( ignored ) 
.RE
.PP
\fBReturns\fP
.RS 4
\fBMat<1, 1, T>\fP the original matrix 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for MatrixVectorHeader from the source code\&.
