.TH "md__readme" 3 "Fri Mar 11 2022" "Version V2.0" "MatrixVectorHeader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__readme \- Template single header library for Vector and Matrix math 

.IP "1." 4
\fBVec\&.hpp\fP includes the basics for template based Vector math and logging
.br
 Also includes quaternion math
.IP "2." 4
\fBMatrix\&.hpp\fP includes the basics for template based Matrix math and printing\&.
.PP
.SH "Documentation"
.PP
Documentation has been generated for HTML, Latex and Man versions If others are desired you can use the doyxgen file\&.
.PP
Man pages can be accessed by using man \&./Documentation/man/man3/file\&.3 
