.TH "Quaternion" 3 "Fri Mar 11 2022" "Version V2.0" "MatrixVectorHeader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Quaternion \- Specialized vector known as a quaternion, used for rotation calculations\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Vec\&.hpp>\fP
.PP
Inherits \fBVec< 4, double >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQuaternion\fP (double w, double x, double y, double z)"
.br
.ti -1c
.RI "const \fBQuaternion\fP \fBgetHProduct\fP (const \fBQuaternion\fP q) const"
.br
.RI "Calculates the Hamilton product between two quaternions\&. "
.ti -1c
.RI "const \fBQuaternion\fP \fBgetConjugate\fP () const"
.br
.RI "creates a conjugated version of the quaternion "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Specialized vector known as a quaternion, used for rotation calculations\&. 
.SH "Member Function Documentation"
.PP 
.SS "const \fBQuaternion\fP Quaternion::getConjugate () const\fC [inline]\fP"

.PP
creates a conjugated version of the quaternion 
.PP
\fBReturns\fP
.RS 4
\fBQuaternion\fP the conjugated quaternion 
.RE
.PP

.SS "const \fBQuaternion\fP Quaternion::getHProduct (const \fBQuaternion\fP q) const\fC [inline]\fP"

.PP
Calculates the Hamilton product between two quaternions\&. 
.PP
\fBParameters\fP
.RS 4
\fIq\fP the other quaternion to use for the product 
.RE
.PP
\fBReturns\fP
.RS 4
\fBQuaternion\fP the product of the two quaternions 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for MatrixVectorHeader from the source code\&.
